### PR TITLE
Adding some support for Exosite Portals to pyonep.

### PR DESCRIPTION
**Pull request by willcharlton**
Tested on Python 2.7.9 and 3.4.1 on OSX.

To see some functionality, run 

```
cd ~/sandbox/pyonep
python pyonep/portals/examples.py
```

This should be a non-breaking change because it puts all of the Portals stuff under `pyonep/pyonep/` and doesn't change anything except the added package to `setup.py`.

### CODE REVIEW

**Comment by willcharlton** [comment]
Ok. I think this is a good 1st pass at adding Portals API support to pyonep. Please advise if you'd like to see anything else before pulling this in.

**Comment by willcharlton** [comment]
Oh and btw if you don't like the names of the modules and the overall structure / namespacing, now would be the time to change it.

**Comment by dweaver** [comment]
Thanks for the PEP8 changes. Re: namespace, it seems like this is the general structure:

```
Domain - handles auth with a particular Portals domain
      |
Portals - stateless pass-through API end point methods
      |
Bindings - helper methods
```

Most of the time I'd instantiate `Bindings` since that has the sugar methods in it and those are generally necessary. It seems like the code will be more readable if `Portals` were the thing being instantiated. Is it important to separate the two? If so, could Portals just contain a `Helpers` object with the glue methods in it?

e.g. something like this
```
Domain - handles auth with a particular Portals domain
      |
Portals - stateless pass-through API end point bindings
 -> Helpers - helper methods
```

I could be missing a subtlety, let me know.

**Comment by willcharlton** [comment]
That's a great idea! But I think we could sidestep helpers and bindings if
I renamed Portals to Endpoints and Bindings to Portals.

**Pull request merged**
